name: CI/CD Test Data Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  test:
    name: Run Pytest on Data Pipeline
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run pytest
        env:
            KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
            KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          pytest
